name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the script on pushes to main

permissions:
  contents: write # Necessary to push the build to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
          cp dist/index.html dist/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
